name: nf-core lint

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2

      - name: Install nf-core tools
        run: |
          python -m pip install --upgrade pip
          pip install "nf-core>=3.0,<4.0"

      - name: Run nf-core lint
        run: |
          nf-core pipelines lint
